
READ_COILS                    =  1
READ_DISCRETE_INPUTS          =  2
READ_HOLDING_REGISTERS        =  3
READ_INPUT_REGISTERS          =  4
WRITE_SINGLE_COIL             =  5
WRITE_SINGLE_REGISTER         =  6
READ_EXCEPTION_STATUS         =  7
DIAGNOSTIC                    =  8
GET_COM_EVENT_COUNTER         = 11
GET_COM_EVENT_LOG             = 12
WRITE_MULTIPLE_COILS          = 15
WRITE_MULTIPLE_REGISTERS      = 16
REPORT_SERVER_ID              = 17
READ_FILE_RECORD              = 20
WRITE_FILE_RECORD             = 21
MASK_WRITE_REGISTER           = 22
READ_WRITE_MULTIPLE_REGISTERS = 23
READ_FIFO_QUEUE               = 24
READ_DEVICE_IDENTIFICATION    = 43

ERROR_FLAG = 0x80

