
READ_COIL = 1
READ_HOLDING_REGISTER = 3
READ_INPUT_REGISTER = 4
WRITE_SINGLE_COIL = 5
WRITE_SINGLE_REGISTER = 6
WRITE_MULTIPLE_COILS = 15
WRITE_MULTIPLE_REGISTERS = 16
# TODO ...

ERROR_FLAG = 0x80

